groups/urls.py
from django.urls import path

from groups.views import get_group, GroupEditView

app_name = 'groups'

urlpatterns = [
    path('<int:id>', get_group, name='group'),
    path('update/<int:id>', GroupEditView.as_view(), name='edit_group'),
]

lms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core_lms.views import index


urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('students/', include('students.urls')),
    path('teachers/', include('teachers.urls')),
    path('groups/', include('groups.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teachers/urls.py
from django.urls import path

from teachers.views import TeacherEditView, TeacherDeleteView, TeacherCreateView, TeacherListView

app_name = 'teachers'

urlpatterns = [
    path('', TeacherListView.as_view(), name='list_teachers'),
    path('create', TeacherCreateView.as_view(), name='create_teacher'),
    path('update/<int:id>', TeacherEditView.as_view(), name='update_teacher'),
    path('delete/<int:id>', TeacherDeleteView.as_view(), name='delete_teacher'),
]

teachers/models/course.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length=32, null=False)
    teachers = models.ManyToManyField(
        to='teachers.Teacher',
        related_name='courses',
        blank=True
    )

teachers/models/teacher.py
import random

from django.db import models
from django.urls import reverse
from faker import Faker
from core_lms.models import Person


class Teacher(Person):
    gender = models.CharField(max_length=64, null=False, default='MALE')
    group = models.ForeignKey(
        to='groups.Group',
        null=True,
        on_delete=models.SET_NULL,
        related_name='teachers'
    )

    class Role(models.IntegerChoices):
        TEACHER = 1, 'Teacher'
        MENTOR = 2, 'Mentor'

    roles = models.PositiveIntegerField(default=Role.TEACHER,
                                            choices=Role.choices)


    @classmethod
    def generate_teachers(cls, count):
        faker = Faker()

        for _ in range(count):
            t = Teacher()
            t.gender = random.choice(["MALE", "FEMALE"])
            t.first_name = faker.first_name_male() if t.gender == "MALE" else faker.first_name_female()
            t.last_name = faker.last_name()
            t.email = faker.ascii_free_email()
            t.birth_date = faker.date_of_birth()
            t.phone_number = faker.phone_number()
            t.save()

    def __str__(self):
        return f"Teacher id - ({self.id}): {self.first_name} {self.last_name} : " \
               f"{self.gender} : {self.email} : {self.phone_number}"

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def get_update_link(self):
        return reverse('teachers:update_teacher',kwargs={'id':self.id})

teachers/forms.py
import django_filters
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from teachers.models import Teacher


class TeacherFilter(django_filters.FilterSet):
    class Meta:
        model = Teacher
        fields = {
            'first_name': ['iexact'],
            'last_name': ['iexact'],
            'email': ['exact'],
        }


class TeacherBaseForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']

        has_phone_number_qs = Teacher.objects.filter(phone_number=phone_number)

        if self.instance:
            has_phone_number_qs = has_phone_number_qs.exclude(id=self.instance.id)

        if has_phone_number_qs.exists():
            raise ValidationError("Phone number is not unique")

        return phone_number

    def clean_email(self):
        email = self.cleaned_data['email']

        banned_domains = [
            "gmail",
            "rambler",
        ]

        domains = []

        for service in banned_domains:
            domains.append("@{0}".format(service))

        ads_tuple = tuple(domains)

        if email[:email.rfind('.')].endswith(ads_tuple):
            raise ValidationError("{0} is a banned domain!".format(email))
        return email


class TeacherCreateForm(TeacherBaseForm):
    pass


class TeacherUpdateForm(TeacherBaseForm):
    class Meta:
        model = Teacher
        exclude = ['birth_date']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, CreateView, ListView

from teachers.forms import TeacherCreateForm, TeacherUpdateForm, TeacherFilter
from teachers.models import Teacher


class TeacherListView(ListView):
    model = Teacher
    template_name = 'teachers/list_teachers.html'
    paginate_by = 10

    def get_filter(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return TeacherFilter(data=self.request.GET, queryset=queryset)

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.select_related('group__headman').order_by('-id')
        filter_ = self.get_filter(queryset)
        return filter_.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.get_filter()
        return context


class TeacherCreateView(LoginRequiredMixin, CreateView):
    model = Teacher
    success_url = reverse_lazy('teachers:list_teachers')
    form_class = TeacherCreateForm
    template_name = 'teachers/create_teacher.html'


class TeacherEditView(LoginRequiredMixin, UpdateView):
    model = Teacher
    success_url = reverse_lazy('teachers:list_teachers')
    form_class = TeacherUpdateForm
    template_name = 'teachers/edit_teacher.html'
    pk_url_kwarg = 'id'


class TeacherDeleteView(LoginRequiredMixin, DeleteView):
    model = Teacher
    pk_url_kwarg = 'id'
    template_name = 'teachers/delete_teacher.html'
    success_url = reverse_lazy('teachers:list_teachers')

teachers/templates/teachers/_teachers_list.html
    <table class="table table-striped">
        <tr>
            <th>First Name</th>
            <th class="text-red border-blue">Last Name</th>
            <th>Group</th>
            <th>Group Headman</th>
            <th class="text-red border-blue">Email</th>
            <th>INN</th>
            <th></th>
        </tr>

        {% for teacher in teachers %}
            <tr>
                <td>{{ teacher.first_name|capfirst }}</td>
                <td>{{ teacher.last_name|title }}</td>
                <td>
                    {% if teacher.group_id %}
                        <a href="{% url 'groups:group' id=teacher.group_id %}">
                            {{ teacher.group.name }}
                        </a>
                    {% else %}
                        <i>Empty</i>
                    {% endif %}
                </td>
                <td>
                    {% if teacher.group_id and teacher.group.headman_id %}
                        {{ teacher.group.headman.name }}
                    {% endif %}
                </td>
                <td>{{ teacher.email|title }}</td>
                <td>{{ teacher.inn }}</td>
                <td>
                    <a href="{% url 'teachers:update_teacher' id=teacher.id %}">✎</a>
                    <a href="{% url 'teachers:delete_teacher' id=teacher.id %}">🗑</a>
                </td>
            </tr>
        {% endfor %}
    </table>

teachers/templates/teachers/create_teacher.html
{% extends '_base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <p>
            <button type="submit" class="btn btn-primary">Create Teacher</button>
        </p>
    </form>
{% endblock %}

teachers/templates/teachers/delete_teacher.html
{% extends '_base.html' %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        <p>Do you want to delete teacher {{ teacher.name }}?</p>
        <p>
            <button class="btn btn-danger" type="submit">Delete</button>
            <a class="btn btn-info" href="{% url 'teachers:list_teachers' %}">Cancel</a>
        </p>
    </form>
{% endblock %}

teachers/templates/teachers/edit_teacher.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Edit teacher{% endblock %}

{% block main %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <p>
            <button type="button" class="btn btn-primary">Update Teacher</button>
        </p>
    </form>
{% endblock %}

teachers/templates/teachers/list_teachers.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block main %}
    <form>
        <p>Search teachers</p>
        {{ filter.form|crispy }}
        <br>
        <p>
            <button type="submit">Search</button>
        </p>
    </form>
    <br>
    <a href="{% url 'teachers:create_teacher' %}">Add new Teacher</a>
    <br>

    {% include 'teachers/_teachers_list.html' with teachers=object_list %}

    {% include '_pagination.html' %}
{% endblock %}